### PR TITLE
Mise à jour de la paje

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by fpagnoux** [comment]
Ok, i separated the brut and net prestations. Is this ok for you? now ?

**Comment by benjello** [comment]
I am sorry it is not ok for me. As you can see [here] (https://github.com/openfisca/openfisca-france/blob/next/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py#L318-L339) all the crds on the prestations familiales are calculated in one bloc. All the prestations should then be net of crds. If fyou really want them net of crds, i would suggest to add a reform which implement paje_versee, cf_verse etc. I am open to any other solution that do not break this computation of brut then net and that do not add too much new variables (borden for computation with survey data).

**Comment by fpagnoux** [comment]
As discussed with @benjello, i'm removing the crds from the `paje` value. We'll add a specific module for mes-aides that compute `paje_versee`and that takes into account crds.

**Comment by fpagnoux** [comment]
Last failing test is due to core bug solved in https://github.com/openfisca/openfisca-core/pull/341.
Waiting for tests to pass

**Comment by cbenz** [comment]
Good work!

**Pull request merged**
