### PR TITLE
Add a notebook about handling periods in OF

### PR DESCRIPTION
**Pull request by edarin**
Reshaping the one of @adrienpacifico.

Feel free to indicate things to add

### CODE REVIEW

**Comment by edarin** [comment]
Maybe not merge right know that I can add change in notebooks in general

**Comment by fpagnoux** [comment]
Not sure `openfisca-france` is the right package to put documentation elements. 
Why not `openfisca-docs`, with a link from the documentation pointing at it ?

**Comment by cbenz** [comment]
@fpagnoux There is already https://github.com/openfisca/openfisca-web-notebook but the point is that users should be able to do:

```
pip install openfisca_france jupyter

cd /path/to/openfisca_france/notebooks
jupyter notebook

# Or one day something like
openfisca demo-notebooks
```

And play with shipped notebooks.

**Comment by fpagnoux** [comment]
If the user does `pip install openfisca_france`, he doesn't know the path to `openfisca_france`, so I'm not sure I understand the usecase. 

Anyway, I don't have a strong objection, I just feel like this already repository contains a lot of thing. 

I really like the activable documentation though 👍

**Comment by edarin** [comment]
I think that this issue can evolve with the [Binder](https://github.com/openfisca/binder-config) that i'm implementing.

The idea will be now to have an environment with different Notebook tutorials people can play with. Right now there is two almost complete Notebook that fill the requirement (the getting-started and the how_to_handle_periods) and others that I've collected but not revised.

I think that a good process will therefore to gather them in the binder repo in order that they are available in the demo environment.

The question remaining open is: shoud they be also in another location in order to have access to them on our own computer when cloning a specific repo ?

**Comment by cbenz** [comment]
Given these arguments, I would suggest to:

- [ ] rename the [binder-config](https://github.com/openfisca/binder-config) to "openfisca/tutorial"
- [ ] store the tutorial notebooks in this repo
- [ ] delete them from OpenFisca-France
- [ ] maybe publish a new OpenFisca-Tutorial package on PyPI
- [ ] update the docs to explain how to start the tutorial (either on mybinder.org, or on the user's machine)

Cc @edarin

**Comment by edarin** [comment]
Update the docs or just referencing the url of the binder ?

**Comment by MattiSG** [comment]
Super ajout en tant que documentation, mais qui ne devrait probablement être inclus directement dans `france` ([raisonnement](https://github.com/openfisca/openfisca-france/pull/679#issuecomment-281678878)). Suivi déplacé dans https://github.com/openfisca/openfisca-gitbook/issues/33.

**Pull request closed without merging**
