### PR TITLE
Mise à jour barèmes bourse collège 2015

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by fpagnoux** [comment]
I'm waiting for a confirmation from @fliightan about the '<='. Please do not merge right now.

**Comment by fpagnoux** [comment]
This shoud be okay to merge now :)

**Comment by MattiSG** [comment]
Yup, @openfisca/collaborators, if there's no issue with this PR, it would really make sense to merge it ASAP, as it is already pretty late to ask for a Bourse already  ;)

**Comment by fpagnoux** [comment]
I'm merging it.

**Pull request merged**
