### PR TITLE
Add set_input_divide

### PR DESCRIPTION
**Pull request by edarin**
Add set_input_divide_by_period 
cf. #614

### CODE REVIEW

**Comment by benjello** [comment]
@edarin: could you rebase and we will definitively merge this PR quickly.

**Comment by benjello** [comment]
And did you understood the origin of the failing test ? (I didn't look)

**Comment by edarin** [comment]
How can I get to this file :   File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest ?

**Comment by benjello** [comment]
@edarin : why you want to do that ?

**Comment by edarin** [comment]
because I want to see which test failed ?

**Comment by edarin** [comment]
sorry j'ai rien dit !

**Comment by benjello** [comment]
Click on the [travis details](https://travis-ci.org/openfisca/openfisca-france/builds/179422554)

**Comment by edarin** [comment]
to be true i didn't manage to understand the problem

**Comment by MattiSG** [comment]
According to https://github.com/openfisca/openfisca-gitbook/pull/32 `set_input_divide_by_period` should only be used for testing purposes.

**Pull request closed without merging**
