### PR TITLE
Baremes ipp

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by cbenz** [comment]
@laem @benjello 
If I merge this in `master`, will you be lost in the XML files?

@benjello told me on the phone about duplicate entries in XML but I don't see any in the diff.

**Comment by benjello** [comment]
There are not proper duplicates but two entries may corresponds to the same legislative parameters although they do not have the same path in the xml tree

**Comment by cbenz** [comment]
@benjello Thanks for the precision. Is there an occurence of this situation in the PR?

**Comment by benjello** [comment]
Many occurences are already in (not brought in by this particular PR): look at agff entry in (cotsoc.xml) [https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/parameters/cotsoc.xml#L1208] and [prelevements_sociaux.xml] (https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/parameters/prelevements_sociaux.xml#L408)

**Pull request merged**
