### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by fpagnoux**
See #342

### CODE REVIEW

**Comment by MattiSG** [comment]
@cbenz @fpagnoux This needs to be sorted out _quick_. I'm trying to rebase some stuff to avoid rotting stale branches, but we're getting our last opportunities to merge before other commits to `openfisca/openfisca-france` make it _real hard_ to get back together.

**Comment by cbenz** [comment]
@fpagnoux Shall I merge ? What about the tests errors?

@MattiSG I'll sort this out with @fpagnoux tomorrow morning if available.

**Comment by fpagnoux** [comment]
Yaaaay !

**Comment by cbenz** [comment]
Hallelujah! (in a non-religious meaning)

**Comment by MattiSG** [comment]
:clap: 
How did you do it in the end? From this PR, it looks like only the Ludwig tests were added  ;)  Did you go through the different branches one by one?

**Comment by fpagnoux** [comment]
"Only the ludwig test were added" has a lot of hidden complexity.
We'll write a more detailed post mortem

**Comment by MattiSG** [comment]
:+1:

**Pull request merged**
