### PR TITLE
Simplify variables declaration (without decorator)

### PR DESCRIPTION
**Pull request by fpagnoux**
See https://github.com/openfisca/openfisca-core/pull/364

### CODE REVIEW

**Comment by fpagnoux** [comment]
Tests need to be updated to fit the new syntax

**Comment by benjello** [comment]
Please propragate these changes to [indirect-taxation] (https://github.com/openfisca/openfisca-france-indirect-taxation) and [france-data] (https://github.com/openfisca/openfisca-france-data) before merging this PR

**Comment by cbenz** [comment]
Of course ☺ I'll do it on every repo I know. 
Thanks for the warning 
Le 2 déc. 2015 8:44 PM, Mahdi Ben Jelloul <notifications@github.com> a écrit :Please propragate these changes to indirect-taxation and france-data before merging this PR

**Comment by cbenz** [comment]
See openfisca/openfisca-core#355

**Comment by cbenz** [comment]
I'm working on the adapation of this big change on every repo.

**Comment by benjello** [comment]
+1

On Thu, Dec 3, 2015 at 4:40 PM Christophe Benz <notifications@github.com>
wrote:

> I'm working on the adapation of this big change on every repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/pull/367#issuecomment-161679824>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by fpagnoux** [comment]
Tests are passing for me, with the appropriate version of core.

**Comment by cbenz** [comment]
Still a bug with france-data and indirect-taxation (the same bug).

@benjello Do you want me to wait to merge?

**Comment by fpagnoux** [comment]
What kind of bug ?

**Comment by benjello** [comment]
What is the bug ?

**Comment by cbenz** [comment]
A bug with `entity_class` and `reference_column`:

```
~/D/o/openfisca-core (master↑17|✚2) $ nosetests openfisca_core/tests/test_countries.py:test_variable_with_reference
E
======================================================================
ERROR: openfisca_core.tests.test_countries.test_variable_with_reference
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/tests/test_countries.py", line 333, in test_variable_with_reference
    class revenu_disponible(Variable):
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/formulas.py", line 995, in __new__
    add_column_to_tax_benefit_system(column, update = update)
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/formulas.py", line 1066, in add_column_to_tax_benefit_system
    entity_column_by_name = column.entity_class.column_by_name
AttributeError: type object 'exceptions.UnboundLocalError' has no attribute 'column_by_name'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

```

**Comment by cbenz** [comment]
I fixed it in https://github.com/openfisca/openfisca-core/commit/a923094c1c99f13f0f06c57a32a0b9e05d71e925

**Comment by cbenz** [comment]
There are still failing tests but they failed previously: https://github.com/openfisca/openfisca-france-data/issues/105 and https://github.com/openfisca/openfisca-france-indirect-taxation/issues/80

I pushed on `new-variables-syntax` branches of nearly all the repo.

While waiting for a GO I'm packaging a release as suggested by @fpagnoux

**Comment by benjello** [comment]
Go

**Comment by fpagnoux** [comment]
Great ! Thanks :)

**Pull request merged**
