### PR TITLE
Update SMIC horaire brut 2016

### PR DESCRIPTION
**Pull request by fpagnoux**
Revalorisation du SMIC, thanks to @HelaG :)

### CODE REVIEW

**Comment by cbenz** [comment]
Good work @HelaG !

@fpagnoux could you update the tests which fail?

**Comment by fpagnoux** [comment]
That's an embauche test, @laem could you please look at it ?

**Comment by laem** [comment]
@fpagnoux I get the error you stated in #368 :
`AttributeError: 'CompactNode' object has no attribute 'IM_max'`
for test : 
```
Test 23: /home/mama/dev/sgmap/openfisca-france/openfisca_france/tests/formulas/af.yaml 
Allocations familiales - Couple, 2 enfants de moins de 11 ans - 2006-01
```

**Comment by benjello** [comment]
See my comment in https://github.com/openfisca/openfisca-core/issues/368 for guidance to complete IM_max.
@adrienpacifico this should help you solve your problems

**Comment by laem** [comment]
> That's an embauche test, @laem could you please look at it ?

I'm on this

**Comment by benjello** [comment]
Nice work @laem !
@cbenz you can merge !

**Comment by benjello** [comment]
Référence : http://www.legifrance.gouv.fr/eli/decret/2015/12/17/ETSX1531022D/jo/texte
Done in baremes IPP

**Pull request merged**
