### PR TITLE
Renames

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by benjello** [comment]
@cbenz  Should I work on this to have it accepted ? It would be nice to have it in oepnfisca/next to avoid tons of conflicts since we are working on tests on varaibles whose names are actually changed in this PR !
Thanks in advance ;-)

**Comment by cbenz** [comment]
The point is that I was trying to clean the branch, if you don't mind waiting a little bit more :pray:

**Comment by benjello** [comment]
@cbenz I can undertsand that, I was just wondering if you still have it in mind of if I forgot to clean something on my side. Thanks.

**Comment by cbenz** [comment]
@benjello Pushed in `next` after rework, and comparing there is no diff with your version. Tests are OK.

**Pull request closed without merging**
