### PR TITLE
Inversion and tests

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by MattiSG** [comment]
Does this mean we can get `sali` from `salaire_net`?  :pray: :)

**Comment by benjello** [comment]
You can now use salaire_net as an input.

**Comment by MattiSG** [comment]
:tada:
@fpagnoux can you try it when this gets merged and you have a bit of time? :)

**Comment by fpagnoux** [comment]
Ok, waiting for merge

**Comment by benjello** [comment]
I am fixing the failing test

**Comment by benjello** [comment]
@cbenz It is fixed now

**Comment by fpagnoux** [comment]
Sorry, I won't have time to test this week :s

**Comment by cbenz** [comment]
Shall I merge ?

**Comment by benjello** [comment]
@cbenz I do not see why you shouldn't ;-)

**Comment by benjello** [comment]
@cbenz : is there any problem on these commits ?

**Comment by cbenz** [comment]
Merged into next (sorry for the delay)! Tests passed successfully.

**Pull request merged**
