### PR TITLE
Several openfisca updates

### PR DESCRIPTION
**Pull request by fpagnoux**
Remake of #299
- Changes in ASF and RSA eligibility
- Renaming (fra, cho_ld, asf_i, asf_elig_i)
- Use of previous_year for CMU 
- Test update

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux : Il me semble que l'on peut recevoir une pension alimentaire et l'ASF. Imaginons une jeune maman divorcée de 20 ans. La pension alimentaire peut venir des parents qui la soutiennent pour qu'elle finisse ses études alors que le père de son enfant dont elle est séparée ne paie pas la pension alimentaire (contribution à l'entretien et l'éducation de l'enfant) ordonnée par le juge des enfants.

**Comment by fpagnoux** [comment]
Merci pour ce retour, on va y réfléchir. Le problème est que les utilisateurs déclarent spontanément les pensions alimentaires reçues pour un enfant à leur nom, et pas au nom de celui-ci...

**Comment by MattiSG** [comment]
In Travis:

> ERROR: Failure: KeyError ('aides_ville_paris')

@fpagnoux ideas?

**Comment by fpagnoux** [comment]
Replace it with 'paris' ?

**Comment by cbenz** [comment]
@fpagnoux I see the problem and I'm fixing it. Basically it's related to the new cache system for reforms during the tests process: we have to declare reforms first in `base.py`. I'm improving the error messages too,

**Comment by cbenz** [comment]
fe5cbfe261032c0f077b1a820eefdeb6813141a1
6b7e3c36a5c2dd574872f6a15632956da1a99633

Can you rebase this PR on next for travis to re-run?

**Comment by fpagnoux** [comment]
Done, waiting for tests results

**Comment by cbenz** [comment]
4 tests are still failing, and I'm not sure about what to do for each of them.

So I call @benjello to have a look :)

Here is a summary of the failing tests:

* [`test_mes_aides_54915af640562f54026f069b.yaml`](https://github.com/openfisca/openfisca-france/blob/several-updates/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54915af640562f54026f069b.yaml#L255) expects [`af: 129.99`](https://travis-ci.org/openfisca/openfisca-france/builds/79702206#L193) and gets `130.0`

Should we replace the value in the test? Why was it `129.99`?

* [`test_mes_aides_553fb8f917d9db60391c3418.yaml`](https://github.com/openfisca/openfisca-france/blob/several-updates/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_553fb8f917d9db60391c3418.yaml#L190) expects [`rsa: 1`](https://travis-ci.org/openfisca/openfisca-france/builds/79702206#L1092) and gets `0`

What's the real value?

* [`test_mes_aides_55b87301677e2db26b9b9654.yaml`](https://github.com/openfisca/openfisca-france/blob/several-updates/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55b87301677e2db26b9b9654.yaml#L145) expects [`aide_logement: 100.98`](https://travis-ci.org/openfisca/openfisca-france/builds/79702206#L2466) and gets `174.13999939`

What's the real value?

* [`test_mes_aides_55b874f263cbf0af6b8ec189.yaml`](https://github.com/openfisca/openfisca-france/blob/several-updates/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55b874f263cbf0af6b8ec189.yaml#L175) expects [`aide_logement: 164.06`](https://travis-ci.org/openfisca/openfisca-france/builds/79702206#L3013) and gets `0`

What's the real value?


Thanks!

**Comment by MattiSG** [comment]
@cbenz Thanks for your work on this  :)

**Comment by fpagnoux** [comment]
I'm checking them in details right now, thanks !

**Comment by fpagnoux** [comment]
test_mes_aides_55b874f263cbf0af6b8ec189.yaml 
=> sould not be a

**Comment by fpagnoux** [comment]
test_mes_aides_54915af640562f54026f069b.yaml seem to be a round problem, but this is a cmu test and it should not test af anyway. Fixing it

**Comment by cbenz** [comment]
Cool!

**Comment by MattiSG** [comment]
:tada:

**Pull request merged**
