### PR TITLE
Add new reform net->brut

### PR DESCRIPTION
**Pull request by laem**
Compute salaire_de_base given a salaire_net.
Simpler than the historical inversion revenus reform, which in addition does not work anymore (probably due to changes in core, especially anti-cycle stuff, fixing it by using this new solver function should be easy).

Add YAML test in a new directory.

### CODE REVIEW

**Comment by laem** [comment]
Mmmh the build fails because of : `ImportError: No module named scipy.optimize`

**Comment by laem** [comment]
The failing travis build (due to Scipy not being installed ?) is the only thing left before a merge.

**Comment by benjello** [comment]
@cbenz @laem : do yo uhave to time to look into the scipy CI integration ?

**Comment by laem** [comment]
Scipy installation was removed from travis in 2139ee3cea184b8b9ea3c8c8d6ced5797a273b91. 
I thought https://github.com/openfisca/openfisca-france/blob/reforme-net-brut/setup.py#L36 would be enough. 
@cbenz must know this.

**Comment by cbenz** [comment]
Indeed `scipy` was used only for `inversion_revenu` reform si I removed it from the standard dependencies, and from the Travis config.

To install your `extras_require` item, you can use `pip install OpenFisca-France[de_net_a_brut]`.

**Comment by laem** [comment]
OK, but should we edit the travis configuration to make the net_a_brut test pass ?

**Comment by benjello** [comment]
I think so.

On Wed, Apr 6, 2016 at 11:10 AM Mael <notifications@github.com> wrote:

> OK, but should we edit the travis configuration to make the net_a_brut
> test pass ?
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/pull/441#issuecomment-206244237>
>
-- 
Mahdi Ben Jelloul

**Comment by cbenz** [comment]
@laem In Travis I recommend you to add `python-scipy` in the `addons.apt.packages` section (to avoid compiling it).

**Comment by laem** [comment]
:+1:

**Comment by benjello** [comment]
Good to merge

**Comment by laem** [comment]
The relevant test for this reform will be run only if scipy is installed in the env. Travis will run it.

**Pull request merged**
