### PR TITLE
Paris Logement Famille (reform)

### PR DESCRIPTION
**Pull request by fpagnoux**
Add-on à Openfisca france pour le calcul de PLF

Aujourd'hui les perfs sont trop mauvaises pour utiliser cette solution dans mes aides. Pour le moment, on travaille sur une branche séparée mais il faudrait qu'on converge ;)

### CODE REVIEW

**Comment by benjello** [comment]
À quoi est due la perte de performance ?

**Comment by cbenz** [comment]
Which actions are slower? Does it mean I should not merge?

**Comment by fpagnoux** [comment]
Last time I tried, running a simulation was twice slower, but I need to check if the work you've done on reforms improved it. 

This is not ready to merge right now, this is not up to date with the recent changes on reforms

**Comment by cbenz** [comment]
@fpagnoux Yes, I think that the new Reform API (in particular [`modify_legislation_json`](https://github.com/openfisca/openfisca-core/blob/3d40d27edf93138aaf80b6271156d3fc37a661fe/openfisca_core/reforms.py#L71-L95) accelerates the `calculate` and `simulate` endpoints by caching the modification of the legislation JSON, instead of letting the reform author doing the `deepcopy` himself.

Documented here (with examples): https://github.com/openfisca/openfisca-core/blob/next/docs/reforms.md

**Comment by cbenz** [comment]
@fpagnoux I did the job to port the reform to the new Reforms API : 927c9ac9ff640af32a4f3e22ba33d02a86765948

**Comment by fpagnoux** [comment]
Great, thanks !

**Comment by fpagnoux** [comment]
Great, thanks !

2015-09-02 10:45 GMT+02:00 Christophe Benz <notifications@github.com>:

**Comment by fpagnoux** [comment]
Tests are ok, but it still takes around 5 seconds to run a simulation. And it gets much worse when I try to run several test cases at the same time. 
It may seriously slow down the tests if we merge it right now.

**Comment by cbenz** [comment]
@fpagnoux came to see me, we found the source of the slowness and I'm implementing a fix.

The reason is that the legislation cache (when using `legislation_at`) is stored in `TaxBenefitSystem` instances (`Reform` is a child class), and `Reform` instances are built at each HTTP request in the API.

We need to cache the `Reform` instances.

For the unit tests, the only instance which is kept between two tests is the base [`tax_benefit_system`](https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0bf30b1fcb888c06b/openfisca_france/tests/base.py#L39). We need to cache reforms for the tests too.

**Comment by cbenz** [comment]
For info @fpagnoux https://github.com/openfisca/openfisca-web-api/blob/next/docs/profiling.md

**Comment by cbenz** [comment]
Merged just now, with the new cache system for reforms in the API. Tests duration: 487.083s

**Comment by fpagnoux** [comment]
Great job, the performance improvement is impressive, thanks a lot !

**Pull request merged**
