### PR TITLE
Mainly minor fixes and renaming

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by MattiSG** [comment]
@benjello Mmh, I see in 3afbd794909fc5672ae2a7e6c6ebe600e5e7ff08 there were improvements in PAJE, ASI and ASPA? Any high-level overview?  :)

**Comment by benjello** [comment]
@MattiSG  went through all the tests we have from mes aides. Should be ok, mainly playing with period to have consistent results at the annual level.
The only point is about the base ressources of ASPA (brut or net) but the tests were ok so it should be ok.

**Comment by MattiSG** [comment]
@benjello Ah, I hoped we would have some crazy improvements we could brag about  ;)  Thanks!  :)

**Comment by benjello** [comment]
@MattiSG : I started some work to reintegrate on Allocation adulte handicapé and a stub for allocation personalisee d'Atutonomie but now I am finishing stagiaire stuff for the next fiche de paie openlab ;-)

**Comment by MattiSG** [comment]
:hear_no_evil:  ;)

**Comment by fpagnoux** [comment]
Hi @benjello,

It seems that switching brut resources to net for aspa had some impact on mes-aides, and caused a bunch of our tests to turn red. After checking with @jdesboeufs , ASI and ASPA should indeed take brut resources into account (see form in attachment). The wiki has been corrected.

If it's ok for you, we will send a PR with a fixup commit soon 

img_20150421_103104848

**Comment by MattiSG** [comment]
> with a fixup commit soon

This would actually just be a revert, I think.

@benjello what was your rationale for switching to `net`?

**Comment by benjello** [comment]
@fpagnoux @MattiSG @jdesboeufs please do the revert/fixup you need. I changed it mainly because I have no source for brut revenues and it was convenient for the simulation with survey data _and_ there was no problem with the tests. We should try to prevent this kind of mistake to happen again by writing a proprer test.

**Comment by MattiSG** [comment]
We have a real problem here then, since 20 Ludwig tests failed on our side. They should have failed in the YAML format too. For example: [`544f7df975fec1b37e6c0288`](https://mes-aides.gouv.fr/tests/544f7df975fec1b37e6c0288/show) should have failed.

**Comment by benjello** [comment]
@MattiSG @eraviart @cbenz : the test you mention passes on my computer. BTW could you remind me (email) how to connect to ludwig (do not automaticcaly connect dna didn't found instructions in my mailbox, sorry)

**Pull request merged**
