### PR TITLE
change calculus of ass to caluculate_add in mini 

### PR DESCRIPTION
**Pull request by adrienpacifico**

### CODE REVIEW

**Comment by cbenz** [comment]
@benjello Could you review this pull request?

**Comment by benjello** [comment]
@adrienpacifico what you should check is the interference with simulation when you have data. Please do some check because I never reviewed/tested the ASS

**Comment by adrienpacifico** [comment]
@benjello, what do you mean by that ? Is an errorless run of
test_agregates.py would be enough ?

2015-06-25 10:15 GMT+02:00 Mahdi Ben Jelloul <notifications@github.com>:

**Comment by benjello** [comment]
ass doesn't seam to be listed in aggregates. You should run the ass with data, look at the values, try to find out if something is wrong etc. Completely untested.

**Comment by benjello** [comment]
Does this breaks test_basics ? What is precisely the bug ? Could you write a test ?

**Comment by adrienpacifico** [comment]
'''
- name: "Revenu disponible"

  period: 2015-03
  input_variables:
    salaire_de_base: 3000
  output_variables:
    revdisp: 2000 #not true value
'''

Here's the test before, error is :
 AssertionError: Requested period 2020 differs from 2020-01 returned by variable ass

PR solves the problem

**Comment by benjello** [comment]
revdisp is a variable that should be computed at the level of the year.
And I do not understand why you get to a response on 2020 for a request on 2015.

**Comment by adrienpacifico** [comment]
My precedent post has been edited : 
1) For 2015, my bad. Copied pasted the wrong entry.
2) Anyway for revdisp period the yaml test crash...

**Comment by adrienpacifico** [comment]
My precedent post has been edited : 
1) For 2015, my bad. Copied pasted the wrong entry.
2) Anyway for revdisp period the yaml test crash...

**Comment by benjello** [comment]
Once again revdisp should be called on a yearly basis
try:
revdisp:
   2015: 2000

Have a lok a test_basics which works

**Comment by adrienpacifico** [comment]
ok, my mistake, woks with 2015. Running a simulation can thus be a bit complex since you need to know at which period you should calculate each variable called.

**Comment by benjello** [comment]
I know but you are supposed to know a bit the variable you call ...

**Comment by cbenz** [comment]
Reopen, vu avec @eraviart et @adrienpacifico

**Pull request merged**
