### PR TITLE
Update plafonds for fillon

### PR DESCRIPTION
**Pull request by MattiSG**
Source: http://travail-emploi.gouv.fr/informations-pratiques,89/fiches-pratiques,91/remuneration,113/l-allegement-de-charges-patronales,1031.html

Should fix sgmap/cout-embauche#29.

@benjello Can you please review this?  :)

### CODE REVIEW

**Comment by benjello** [comment]
Same values for 2015 as what we have in the IPP tables.
I looked at the reference provided in [cout-embauche] (https://github.com/sgmap/cout-embauche/issues/29) and it should be ok.

**Comment by MattiSG** [comment]
Yet this fails tests with:

> AssertionError: allegement_fillon@2015-04: [ 407.37588501] differs from [ 409.55999756] with an absolute margin [ 2.18411255] > 0.005

I can't find the test file from which it's coming… (poke @cbenz)

(btw, “absolute margin” doesn't seem to be what it sounds like here…)

**Comment by MattiSG** [comment]
I found it, it was `salsuperbrut.yaml`. Should be fixed by using relative error margin (1%) rather than absolute (0.005€…).

Conclusions:

1. A number loaded from a YAML test has floating issues (409.56 loaded as 409.5599…).
2. There is no way to obtain the file from which a failing test has been executed.

**Comment by cbenz** [comment]
commit 35297744ab8d3f6582824b03e6166483eb2c9853 (`test_yaml.py`) displays the YAML file path on error.

**Pull request merged**
