### PR TITLE
Remove print

### PR DESCRIPTION
**Pull request by fpagnoux**
Finally found it

### CODE REVIEW

**Comment by MattiSG** [comment]
:+1: :wink:

**Comment by cbenz** [comment]
Great, see 7aa779931c1eda4d5cff15875c1851223be1053d new Makefile target to check `print` presence on Travis, only in `openfisca_france/model` dir for now.

**Comment by fpagnoux** [comment]
So I if understand correctly, now the presence of a print in the code will make the travis build fail ?

**Comment by cbenz** [comment]
Yes, only in `openfisca_france/model`. It it turns out to be efficient I will generalise it to the whole codebase.

**Pull request merged**
