### PR TITLE
RSA increase 2016-09-01

### PR DESCRIPTION
**Pull request by michelbl**
RSA increase of +0.2% on 2016-09-01

see sgmap/mes-aides-ui#372

### CODE REVIEW

**Comment by michelbl** [comment]
Do I need to write a new test ?

**Comment by michelbl** [comment]
Fails with messag "Version  already exists. Please update version number in setup.py before merging this branch into master."

What is the process to update the version number ?

**Comment by MattiSG** [comment]
> Do I have to write a new test ?

Yes, would be better.


> What is the process to update the version number ?

See https://doc.openfisca.fr/en/contribute/guidelines.html. This should probably be a patch number bump.

**Comment by fpagnoux** [comment]
Duplicate of #579

**Pull request closed without merging**
