### PR TITLE
Stop printing a humongous amount of log in CI

### PR DESCRIPTION
**Pull request by fpagnoux**
I think we all agree that this is not very useful information to debug when travis doesn't pass: 

image

To remove that, I see two easy solutions, and I would like your advice @cbenz @laem @benjello.

- Set `debug` to false in `test_yaml.py`. It is the implementation suggested here. I don't exactly know what activating `debug` means, does it have other effects that were useful to anyone when running tests ?
- Get rid of the `log.info(...)` in [`formulas.py`](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/formulas.py#L150). Same question: has anyone been using this to debug code recently ?

Thanks for your feedback.

### CODE REVIEW

**Comment by laem** [comment]
All I need on the travis log is the name of the failing test to run and debug it on my machine.

**Comment by benjello** [comment]
@fpagnoux : I use actually use the [debug info produced by formulas.py](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/formulas.py#L150) and I do not use the trace tool. I agree it is not perfect but it is useful (not only for openfisca-france). A nicer debugging interface is welcome.

**Comment by fpagnoux** [comment]
Ok, so let's keep the debug info printing as it is. Do you use it as well while running tests with `test_yaml.py`?

**Comment by fpagnoux** [comment]
@benjello, do you use the debug info printing in the context of yaml tests ?
If so, we can have an optional parameter to `test_yaml.py`. If not, then we're good with this 😎

**Comment by benjello** [comment]
Let us have an option. O use -v to print the debug info.

Le ven. 15 avr. 2016 09:57, Florian Pagnoux <notifications@github.com> a
écrit :

> @benjello <https://github.com/benjello>, do you use the debug info
> printing in the context of yaml tests ?
> If so, we can have an optional parameter to test_yaml.py. If not, then
> we're good with this 😎
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/pull/462#issuecomment-210344899>
>
-- 
Mahdi Ben Jelloul

**Comment by MattiSG** [comment]
Please add options only if the two use cases are legit and frequently used. Otherwise, make a design choice.

**Comment by fpagnoux** [comment]
Sorry to insist, but I agree with @MattiSG, I'd like to make sure there is an actual need for **printing all this logs** in the context of **yaml tests** before spending some time on implementing an optional parameter system. I don't think we should do it if it's "just in case". So, can someone confirm me they frequently use these logs to debug, while running a yaml test ?
@benjello

**Comment by benjello** [comment]
@fpagnoux : I do use the debug info when I want to debug a specific yaml test interactively:
test_yaml.py -n "mon test" -v
It is very useful to me. I agree the info shouldn't be in the log especially for openfisca-france where the number of formulas is pretty long.

**Comment by fpagnoux** [comment]
Ok, I used the pre-existing `-v` option to activate debug mode only optionally. So:

```sh
python tests/test_yaml.py tests/mes-aides.gouv.fr/x.yaml

==========================================================================================
Test 1: /Users/fpagnoux/dev/mes-aides/openfisca/openfisca/france/openfisca_france/tests...
==========================================================================================
Traceback (most recent call last):
  File "tests/test_yaml.py", line 319, in <module>
    checker(yaml_path, name, period_str, test, force, args.verbose)
  File "tests/test_yaml.py", line 192, in check_calculate_output
    relative_error_margin = test.get('relative_error_margin'),
  File "tests/test_yaml.py", line 124, in assert_near_calculate_output
    abs(target_value - value), absolute_error_margin)
AssertionError: rsa@2014-07: [ 252.30999756] differs from [ 20000.] with an absolute...
```

**Pull request merged**
