### PR TITLE
Change cumul rule for CF/PAJE

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-api#71

Change cumul rule: no CF is there is PAJE
(no matter which one is the biggest)

### CODE REVIEW

**Comment by benjello** [comment]
Was this rule also valid in the past ?

**Comment by fpagnoux** [comment]
I don't have any element making me think the rule changed since the introduction of the PAJE in 2004.

**Comment by fpagnoux** [comment]
If you have any indication about it, I'm willing to adapt the formula, but searching for the exact legal text that introduced this rule is not in our scope and really costly.

**Comment by benjello** [comment]
It is ok. You are just closer to expert for those matter than I am (no need for legal ref at this point).
We just applied the rule, use the most favorable option for the household when in doubt.

**Comment by fpagnoux** [comment]
Yes, we were also thinking the same, but when we compared our results to actual CAF situations, they told us about this specific rule. I agree it is disturbing, as it's clearly disadvantageous for people.

**Pull request merged**
