### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### openfisca/openfisca-france now has a Chat Room on Gitter

@laem has just created a chat room. You can visit it here: [https://gitter.im/openfisca/openfisca-france](https://gitter.im/openfisca/openfisca-france?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/openfisca/openfisca-france?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux @laem @MattiSG @cbenz : should we accept this PR ?

**Comment by fpagnoux** [comment]
It would help random contributors to find the gitter, so yep, GTM for me.
Thanks @laem

**Comment by cbenz** [comment]
No reason to refuse, but don't forget to use the [forum](http://forum.openfisca.fr/) :)

**Comment by fpagnoux** [comment]
I'll put it on one line though

**Comment by MattiSG** [comment]
> No reason to refuse, but don't forget to use the forum :)

Then we need to add the precise use cases for each mean of communication along with the links in the README.

**Pull request merged**
