### PR TITLE
Rename alv to pensions alim versees

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux could you use a longer name pensions_alimentaires_versees ? Thank you ;-)

**Comment by fpagnoux** [comment]
Done !

**Comment by fpagnoux** [comment]
I have a question though : 
For mes-aides, we would like pensions_alimentaires_percues to be a FloatCol, but alr was a IntCol. Is there any reason for this, or can we just change it to FloatCol ? 
Also, alv applied to the entity FoyerFiscaux, while we would like our pensions_alimentaires_versees to apply to individuals.
Taking this into account, do you think it makes sense to have the same variable for our _pensions_alimentaires_versees_ and the existing _alv_ ?

**Comment by fpagnoux** [comment]
Following our phone conversation, I introduced a new variable pensions_alimentaires_versees_individu. Does it look ok for you ?

**Comment by benjello** [comment]
Ok @fpagnoux

**Comment by cbenz** [comment]
Merged into `next`

**Pull request closed without merging**
