### PR TITLE
Seulement une demi majoration pour âge pour les enfants en garde alternée ouvrant droit

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/openfisca-france#37

### CODE REVIEW

**Comment by fpagnoux** [comment]
Tests to come

**Comment by fpagnoux** [comment]
Ok, I used a parameter to have a different behaviour according to a date.
For pre-2007, I kept the old behaviour, which is to consider the child to be 100% part of the family.

>Just by the way, I tried to run a test for 2005-04, and calculating `af` throws a ParameterNotFound exception.

**Comment by benjello** [comment]
2006 is the first sure date.


Le mar. 26 janv. 2016 21:39, Florian Pagnoux <notifications@github.com> a
écrit :

> Ok, I used a parameter to have a different behaviour according to a date.
> For pre-2007, I kept the old behaviour, which is to consider the child to
> be 100% part of the family.
>
> Just by the way, I tried to run a test for 2005-04, and calculating af
> throws a ParameterNotFound exception.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/pull/422#issuecomment-175218188>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by fpagnoux** [comment]
Low-risk PR, I'm merging

**Pull request merged**
