### PR TITLE
ASS basé sur salaire imposable

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to https://github.com/sgmap/openfisca-france/issues/5

### CODE REVIEW

**Comment by cbenz** [comment]
As we discussed with @fpagnoux and since the tests don't pass with this PR, I let you use a temporary branch to deploy your next version of Mes-aides. Then I let you ensure the tests pass and PR again.

**Comment by fpagnoux** [comment]
The tests have just been updated for this too on mes-aides.gouv.fr
@cbenz, can you please merge this when you have time ? 
Thanks !

**Comment by cbenz** [comment]
Can you add the new tests from Ludwig in this PR?

**Comment by fpagnoux** [comment]
I updated the concerned ludwig tests. It should be good to merge.

**Comment by cbenz** [comment]
Great!

**Pull request merged**
