### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by fpagnoux**
Unclear naming backfired at us last week with our administrative partners.
The most used variables should have a clear name. 

Also, what is `choi`? Is it a doublon of `cho`/`chomage_imposable`? Is it for inversion ? The same question goes for `rsti`.

Thanks !

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux : choi and rsti are doublon and and they are used in inversions. We should put them there.

The other little problem is related to rst which means retraite au sens strict which is different from retraite à titre onéreux (rto). We may keep the name you introduced if the label is precise enough and change rto.

**Comment by fpagnoux** [comment]
Ok, what would be a good label for `retraite_imposable` that would make everything clear ? "Retraite (au sens strict, rentes à titre onéreux exclues) imposables" ?
You probably know more than me about this ;)

**Comment by benjello** [comment]
@fpagnoux : i would go for "Retraite au sens strict imposables (rentes à titre onéreux exclues)"

**Comment by fpagnoux** [comment]
Done !

**Comment by fpagnoux** [comment]
@benjello, is this ok to merge for you ? 
@cbenz, when you come back tell me if there is any issue with this ;)

The sooner is the better for merging, because renaming generally has a lot of potential conflict with other work in progress

**Comment by benjello** [comment]
It is ok for me. Since I have to change it on many other repo, please  @cbenz ring me when you merge this !

**Comment by cbenz** [comment]
@benjello Still OK to merge *

**Comment by benjello** [comment]
Yep

**Pull request merged**
