### PR TITLE
Change link (http -> https)

### PR DESCRIPTION
**Pull request by edarin**

### CODE REVIEW

**Comment by cbenz** [comment]
@edarin I bumped the version number for you, I'm now waiting for Travis to test (Wow, testing a README is such ... hmmm .... relevant ^^) and I'll merge it.

**Comment by cbenz** [comment]
@fpagnoux As a side comment I'd like us to discuss about how to improve these small changes which should not (or please convince me!) require a bump.

**Comment by fpagnoux** [comment]
One thing we could do is to force the BUMP only if files have been modified **inside** the package directory. This way README.md would be ignored.
Are there other cases where you think the version bump is an unnecessary constraint ? 
@edarin @cbenz

**Comment by cbenz** [comment]
That would be a first step, let's try it. For now I don't see anything else.

**Pull request merged**
