### PR TITLE
Abattement base de revenu pour ASPA et ASI en cas de pensions alim versées

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by MattiSG** [comment]
Partial fix of sgmap/mes-aides-api#2.

**Comment by MattiSG** [comment]
[Test associé](https://mes-aides.gouv.fr/tests/552cecfb366d30921bab905b/show).

**Comment by MattiSG** [comment]
@fpagnoux Please add a small comment explaining why you close a PR when you do, so we can understand what's happening (bug found? will it be reopened?)  :)

**Comment by fpagnoux** [comment]
Sorry, the idea was just to make new clean PRs after we agree on the variable renaming. Maybe in the future I push correcting commits instead to have more visibility on the PR history ?

**Comment by MattiSG** [comment]
> Maybe in the future I push correcting commits instead to have more visibility on the PR history ?

Exactly! This way one can follow through the conversation and the impact it had on the code  :)

**Comment by fpagnoux** [comment]
PR closed, see https://github.com/openfisca/openfisca-france/pull/213 for continuation

**Pull request closed without merging**
