### PR TITLE
implement true_decote that is the decote amount provided by dgfip

### PR DESCRIPTION
**Pull request by adrienpacifico**
implement true_decote that is the decote amount provided by dgfip  (at least on their simulator)
which is the fiscal gain accountable to the decote mechanism.

### CODE REVIEW

**Comment by adrienpacifico** [comment]
Do not merge if it is ok. We need to discuss :

1) Isn't there a simpler way to have décote in the dgfip meaning
2) should we name actual decote 'raw_decote' or anything else
3) is true_decote the best name.

I would go for naming actual decote 'raw_decote' and actual true_decote 'decote'.

**Comment by benjello** [comment]
Keep the old decote as is.
Rename the "dgfip" decote to decote_gain_fiscal

**Comment by adrienpacifico** [comment]
Thanx @benjello,
will do so Asap.

**Comment by adrienpacifico** [comment]
Done ( I feel unhappy about the name, but I have nothing better to propose :-) ).

**Comment by cbenz** [comment]
@adrienpacifico Should I merge or is it still pending?

**Comment by adrienpacifico** [comment]
You can merge, but you might want @benjello to confirm it's ok :-) .

**Comment by benjello** [comment]
If tests are ok xith the dgfip simulator, it is fine with me

**Comment by adrienpacifico** [comment]
It is for 4 cases (no IR, IR below decote, IR over decote, and IR without decote).

@cbenz thus you can merge :)

**Comment by adrienpacifico** [comment]
@cbenz why isn't it merged ? Is there a problem ?

**Comment by benjello** [comment]
good to merge @cbenz

**Pull request merged**
