### PR TITLE
Tns agricoles et autres

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to https://github.com/sgmap/mes-aides-ui/issues/36
Connected to https://github.com/sgmap/mes-aides-ui/issues/48

### CODE REVIEW

**Comment by cbenz** [comment]
As we discussed with @fpagnoux and since the tests don't pass with this PR, I let you use a temporary branch to deploy your next version of Mes-aides. Then I let you ensure the tests pass and PR again.

**Comment by fpagnoux** [comment]
Hi @cbenz 
The tests have been updated on mes-aides.gouv.fr
Can we merge this branch ?

**Comment by cbenz** [comment]
Yes, I will do that soon, I'm in the forum ouvert ;-)
Le 19 mai 2015 11:36, Florian Pagnoux <notifications@github.com> a écrit :Hi @cbenz 
The tests have been updated on mes-aides.gouv.fr
Can we merge this branch ?

**Comment by fpagnoux** [comment]
Ok, thanks !

**Comment by cbenz** [comment]
Can you add the new tests from Ludwig in this PR?

**Comment by cbenz** [comment]
thanks

**Pull request merged**
