### PR TITLE
Update tests (new yaml dialect)

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by fpagnoux** [comment]
The failing test will pass when we put aah in prod. 
Good to see that openfisca is now ahead of mes-aides :)

**Comment by cbenz** [comment]
So, do I need to wait for an `aah` related PR?

**Comment by cbenz** [comment]
```
ERROR: Failure: ValueError (Error in test /home/travis/build/openfisca/openfisca-france/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_559fb665f394e1a7011b573a.yaml:
{'test_case': {'individus': {1: {'taux_invalidite': u'Unexpected item'}}}}
```

Is this test obsolete?

**Comment by benjello** [comment]
Renamed to taux_incapacite

Le mar. 24 nov. 2015 18:31, Christophe Benz <notifications@github.com> a
écrit :

> ERROR: Failure: ValueError (Error in test /home/travis/build/openfisca/openfisca-france/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_559fb665f394e1a7011b573a.yaml:
> {'test_case': {'individus': {1: {'taux_invalidite': u'Unexpected item'}}}}
>
> Is this test obsolete?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france/pull/362#issuecomment-159349384>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by cbenz** [comment]
OK I understand that this PR re-downloaded tests which were updated in the last merged `aah` branch.

Let's talk about ignoring tests :)

**Pull request merged**
