### PR TITLE
Update plafond de la sécurité sociale

### PR DESCRIPTION
**Pull request by laem**
I'm surprised this doesn't break tests.

### CODE REVIEW

**Comment by adrienpacifico** [comment]
Is it because there is no tests ? 

We might have to think of a global testing strategies. We might have many very precise tests for some parts of the legislation, but many @formulas do not even have one test.

**Comment by laem** [comment]
I'll add some for agirc/arcco,they depend on the plafond

**Comment by benjello** [comment]
No tests for the new years. This PR is good to merge for me. You can add AGIRC-ARRCO later. And may be you will have them form barems-ipp bu then ;-)

**Comment by benjello** [comment]
Réf http://www.legifrance.gouv.fr/eli/arrete/2015/12/17/AFSS1530064A/jo/texte
iinlcuded in baremes IPP

**Pull request merged**
