### PR TITLE
Calcul de la PPA

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-ui#199

### CODE REVIEW

**Comment by fpagnoux** [comment]
I don't think the tests not passing is related to this PR. See https://github.com/openfisca/openfisca-core/issues/368

**Comment by fpagnoux** [comment]
@benjello, there is some renaming in this PR: 
rfon_ms -> rsa_revenus_fonciers
br_rmi -> rsa_base_ressources
br_rmi_i -> rsa_base_ressources_i
br_rmi_pf -> rsa_base_ressources_prestations_familiales
br_rmi_ms -> rsa_base_ressources_minima_sociaux
ra_rsa_i -> rsa_revenu_activite_i
ra_rsa -> rsa_revenu_activite

**Comment by cbenz** [comment]
Good to merge?

**Comment by benjello** [comment]
@fpagnoux : could you check if the renaming is appropriate for rfon_ms -> rsa_revenus_fonciers since ms stands for minima sociaux it may appear in other formulas than rsa (ASPA ?).

**Comment by fpagnoux** [comment]
See PR on openfisca core.

**Comment by fpagnoux** [comment]
Reworking on this.

**Pull request closed without merging**
