### PR TITLE
Prise en compte des revenus du conjoint pour l'ASS : ARE, Retraite, IJ et ASS abattus 

### PR DESCRIPTION
**Pull request by fpagnoux**
Abattement de 30% sur les revenus quand ils sont substitués

### CODE REVIEW

**Comment by benjello** [comment]
@fpagnoux: I just noticed that you changed the parameter for years before 2014. Could you confirm that the value is right for those years too ? Otherwise it is better to change your SimpleFormulaColumn to a DatedFormulaaColumn. Thanks.

**Comment by fpagnoux** [comment]
The [article] (http://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000018525086&cidTexte=LEGITEXT000006072050&dateTexte=20150417) mentioning this 30% cut has been modified last time in marsh 2009. 
This [modification] (http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000020381155&dateTexte=&categorieLien=id) didn't change this cut. 

Do you know any tool that could help me browse the history of this article to check when it was introduced ? Sp far I can only grant that the value is right from 2009.

**Comment by eraviart** [comment]
May be this can help : https://github.com/steeve/france.code-civil/tree/everything/Code%20Du%20Travail/Partie%20R%C3%A9glementaire/Cinqui%C3%A8me%20Partie/Livre%20IV/Titre%20II/Chapitre%20III

**Comment by fpagnoux** [comment]
Thanks a lot ! 
So the article, and the 30% cut, have been introduced by [this decret](http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000018442415), which has been ordered on the 7th of march, 2008. Should I put this date in the param file ? Are decret immediately applied ?

**Comment by benjello** [comment]
@fpagnoux the date that should be in the param file is the "date d'effet". And if you have a clue about the value before this date please please fill it. Otherwise you should mention it in the param file and/or introduce a DatedFormulaColumn

**Comment by fpagnoux** [comment]
Thanks, i finally found the [application date] (http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000018254394#LEGIARTI000018255685)

```
Article 11 En savoir plus sur cet article...

Les dispositions du présent décret entrent en vigueur le 1er mai 2008.
```
As this decret introduces a 30% abatement on some incomes, I think the cleanest and easiest solution would be to have a 0 value before this date, as there was no abatement then.

**Comment by fpagnoux** [comment]
See PR #254

**Pull request merged**
