### PR TITLE
Manage circular formula calls

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to openfisca/openfisca-core#347

Depends on openfisca/openfisca-core#358 and https://github.com/openfisca/openfisca-web-api/pull/45

### CODE REVIEW

**Comment by cbenz** [comment]
There is still an error with test [`apprenti.yaml`](https://github.com/openfisca/openfisca-france/blob/manage-circular-formula-calls/openfisca_france/tests/fiches_de_paie/apprenti.yaml)

```
AssertionError: Circular definition detected on formula allegement_fillon<2015-01>.
Formulas and periods involved: allegement_fillon<2015-03>.
Hint: use "max_nb_recursive_calls = 0" to get default value, or "= N" to allow N recursion calls.
```

Didn't you modify yesterday [this file](https://github.com/openfisca/openfisca-france/blob/e4bc0424b47375b07605bee9e09f233f8dfba1bd/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py#L199) and forget to push?

**Comment by cbenz** [comment]
I did 2619a409b7456ef3dd6fa872991aa38f6afa2f59

**Comment by fpagnoux** [comment]
J'avais effectivement oublié de pusher un commit.

**Comment by cbenz** [comment]
Merged into master

**Comment by cbenz** [comment]
Tests are OK, thanks for the very good work @fpagnoux !

**Comment by benjello** [comment]
Tests don't pass on my computer. For example test_basics do not pass ...

**Pull request closed without merging**
