### PR TITLE
Abattement de la base ressources si pension alimentaire pour l'ASS

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by MattiSG** [comment]
Partial fix of sgmap/mes-aides-api#2.

**Comment by MattiSG** [comment]
@fpagnoux Why close?

**Comment by MattiSG** [comment]
[Test associé](https://mes-aides.gouv.fr/tests/552ceb4103d575851b786071/show?keyword=ass).

@eraviart Pourrais-tu stp expliquer à @fpagnoux comment intégrer des tests Ludwig dans OpenFisca ? On pourrait ainsi assortir ces pull requests des tests associés  :)

**Comment by cbenz** [comment]
I've cancelled the merge

**Comment by fpagnoux** [comment]
This PR was a mistake, as I accidentally did on master instead of next. That's why I closed it, and opened another one on next (#210 https://github.com/openfisca/openfisca-france/pull/210).

**Pull request closed without merging**
