### PR TITLE
Several PR with updated tests

### PR DESCRIPTION
**Pull request by fpagnoux**
Contains changes from : 
#341 
#333 
#340 
#331 
and test updates.

### CODE REVIEW

**Comment by MattiSG** [comment]
What was the rationale for merging all these PRs into one? This goes against the chosen branching model, and makes it pretty hard to identify the origin of a potential problem.

(thanks for cross-marking them though!  :)  )

**Comment by cbenz** [comment]
@fpagnoux Did you understand what fails?

**Comment by fpagnoux** [comment]
@MattiSG,
These feature branches each introduce different changes in the test base.
The only way to quickly update the tests today is to put the new version in prod, run the julia script to download the new tests, and then commit them.
But once everything is on prod, there is no way to distinguish which test update depends on which PR. Thus an aggregated PR is necessary to pass the travis tests.

**Comment by fpagnoux** [comment]
@cbenz, 
It fails because of [this](https://github.com/openfisca/openfisca-core/issues/347). There is a circular definition problem with AL and RSA. I've been working on it, but it's tricky. We can talk more about it if you want.

**Comment by fpagnoux** [comment]
Closing this one to open one on master

**Pull request closed without merging**
