### PR TITLE
Calcul de la PPA

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-ui#199

Some renaming : 
rfon_ms -> rsa_revenus_fonciers
br_rmi -> rsa_base_ressources
br_rmi_i -> rsa_base_ressources_i
br_rmi_pf -> rsa_base_ressources_prestations_familiales
br_rmi_ms -> rsa_base_ressources_minima_sociaux
ra_rsa_i -> rsa_revenu_activite_i
ra_rsa -> rsa_revenu_activite
alt -> garde_alternee

### CODE REVIEW

**Comment by fpagnoux** [comment]
This is mostly the addition of a new prestation, there is not so much impact on the rest of openfisca, except:
- PPE is now outdated
- RSA formula have been updated
- Some renaming

There is also some refactoring, but green tests seem to show that there is no problem with that.

I could of course do with a general review, but since everyone is busy, I doubt this will happen, and we are pretty late with the integration of this into openfisca codebase (it's been in prod for a while in mes-aides).

If no one has objection, I'll thus merge this Tuesday night.

**Comment by benjello** [comment]
I will check it by tuesday. Thanks a lot for this work.

**Comment by benjello** [comment]
I am looking at it right now ...

**Comment by benjello** [comment]
Few comments:
 - Please check that the start and stop date coincide well for ppe, rsa_act and ppa since you have all the relevant information.
 - Might consider putting ppa parameters closer to the rsa in parma.xml

Otherwise no objection for merging

**Comment by fpagnoux** [comment]
The last PPE has been paid in 2015, and the shift from RSA activite to PPA was immeadiate, so I think we are good.
You're right about the params, it's weird they are alone while all the others ones are in the same file, but wasn't there a plan to split this big params file ?

**Comment by benjello** [comment]
We are trying to split them [here] (https://github.com/openfisca/openfisca-france/tree/baremes-ipp/openfisca_france/parameters). We will use separate files but all the prestations will be kept together.

**Pull request merged**
