### PR TITLE
Arrco bugs for second tranche

### PR DESCRIPTION
**Pull request by laem**
Fixing embauche bugs [114](https://github.com/sgmap/cout-embauche/issues/114) and [17](https://github.com/sgmap/cout-embauche/issues/17).
Respectively these ludwig tests : 
http://embauche.sgmap.fr/tests/55c4838b6149d1903b3d3e5c/show
http://embauche.sgmap.fr/tests/55c382a46149d1903b3d2d82/show

### CODE REVIEW

**Comment by cbenz** [comment]
@benjello A meeting all together is a good idea, because with @eraviart we started to think about refactoring start and end dates of the root of the XML file.

Should I merge this PR?

**Comment by benjello** [comment]
I just want @laem mel te be aware that the common node was created to host the baremes that are be common to cadre and noncadre so overriding common is natural.

**Comment by laem** [comment]
OK for a meeting this week. 

> overriding common is natural

Yes @benjello we agree on this. So until we fix preprocessing this commit is a good fix I guess.

**Comment by cbenz** [comment]
Thanks!

**Pull request merged**
