### PR TITLE
build: update to openfisca-core v43

### PR DESCRIPTION
**Pull request by bonjourmauko**
Depends on openfisca/openfisca-core#1223

* Changement mineur.
* Détails :
  - MàJ d'OpenFisca-Core

- - - -

Ces changements :

- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] ~Documentez votre contribution avec des références législatives.~
- [x] ~Mettez à jour ou ajoutez des tests correspondant à votre contribution.~
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

### CODE REVIEW

**Comment by bonjourmauko** [comment]
@benjello @benoit-cty As with the other PR, this is just to test that the changes in core do not break the lib. The conda build will always fail, because we're installing from a URL. Once changes to core are accepted and merged, this PR becomes obsolete, and it has to go back to the regular PyPi -now published- package with the required version. Only then the Conda build will work. If you wait for the Conda build to accept changes in core, it won't ever happen.

**Comment by benjello** [comment]
@bonjourmauko : je crois que je sais d'où vient le problème. Je vais pousser une correction.

**Comment by bonjourmauko** [comment]
For the Conda build..., it fails because now core is being correctly published to conda. You need to fix the recipe.

**Comment by benjello** [comment]
@sylvainipp @clallemand @benoit-cty your call !

**Review by benoit-cty — COMMENTED** [review]
Hello,
All the code looks good to me, but seems to do not work:
```
git switch chore/update-core-42.0.0
python3 -m venv .venv
source .venv/bin/activate
make install
```
Return:
```
The conflict is caused by:
    openfisca-france[dev] 169.0.0 depends on pytest<8.0 and >=7.2.2; extra == "dev"
    openfisca-core 43.2.0 depends on pytest<9.0 and >=8.3.3
    openfisca-france[dev] 169.0.0 depends on pytest<8.0 and >=7.2.2; extra == "dev"
    openfisca-core 43.1.2 depends on pytest<9.0 and >=8.3.3
    openfisca-france[dev] 169.0.0 depends on pytest<8.0 and >=7.2.2; extra == "dev"
    openfisca-core 43.1.1 depends on pytest<9.0 and >=8.3.3
    openfisca-france[dev] 169.0.0 depends on pytest<8.0 and >=7.2.2; extra == "dev"
    openfisca-core 43.1.0 depends on pytest<9.0 and >=8.3.3
    openfisca-france[dev] 169.0.0 depends on pytest<8.0 and >=7.2.2; extra == "dev"
    openfisca-core 43.0.0 depends on pytest<9.0 and >=8.3.3
```

```
python -V
=> Python 3.10.5
```

And the CI fail : https://github.com/openfisca/openfisca-france/actions/runs/11369496601/job/31670917208?pr=2357

for `make check-style` that works locally.

**Comment by bonjourmauko** [comment]
Yep, the thing is `pytest` is a production requirement of core. Fixing it.

**Review by benoit-cty — APPROVED** [review]
Thanks, it works :+1:

**Comment by Shamzic** [comment]
Thanks everyone 🙏

**Pull request merged**
