### PR TITLE
Abattement en cas de pension alimentaire versée pour la CMU et l'ACS

### PR DESCRIPTION
**Pull request by fpagnoux**
Ajout de la colonne pensions_alimentaires_versees

### CODE REVIEW

**Comment by cbenz** [comment]
Thanks! But I'm surprised you commit above the branch master, not next. Perhaps I'll explain that to you this afternoon?

**Comment by benjello** [comment]
Please go through me if commits add new variables since they might already exist ! And it is the case here.

**Comment by MattiSG** [comment]
@cbenz Are we sure this should have been merged? I took @benjello's comment as a need to rename… ?

**Comment by cbenz** [comment]
No, I did it this morning and read the comments afterwards. I'm gonna cancel it. 
Le 14 avr. 2015 2:30 PM, Matti Schneider <notifications@github.com> a écrit :@cbenz Are we sure this should have been merged? I took @benjello's comment as a need to rename… ?

**Comment by benjello** [comment]
No it shouldn't. @fpagnoux please reach out to me when you find the need to create a new variable. Thanks.

**Comment by cbenz** [comment]
I've cancelled the merge

**Comment by fpagnoux** [comment]
PR closed, see #213 for up to date PR

**Pull request merged**
