### PR TITLE
Revalorisation plafonds ASS

### PR DESCRIPTION
**Pull request by fpagnoux**
Fixes https://github.com/sgmap/openfisca-france/issues/1

Tested locally

### CODE REVIEW

**Comment by cbenz** [comment]
@benjello Just to check, is it OK for you to merge this pull request?

**Comment by benjello** [comment]
@cbenz:  for ASS, @fpagnoux and @MattiSG have definitively more expertise, so it should be ok !

**Comment by cbenz** [comment]
Merged in `next`, thanks everybody!

**Comment by MattiSG** [comment]
Thanks @cbenz!  :)

**Pull request merged**
