### PR TITLE
Merge master on baremes-ipp

### PR DESCRIPTION
**Pull request by fpagnoux**
Following conversation on https://github.com/openfisca/openfisca-france/pull/548#issuecomment-243391647

### CODE REVIEW

**Comment by benjello** [comment]
@cbenz deleted baremes-ipp-merge-master but it does not show in baremes-ipp branch wich is still at version 4.1.5

**Comment by benjello** [comment]
@fpagnoux could you give it a new try ? Thanks !

**Comment by fpagnoux** [comment]
Sorry, i was not able to work on it yesterday, and I'll be gone for 3 weeks. 
The main source of conflict is that I moved a few classes to other files, and there were changes in bareme ipp on these classes. 
To merge, you can look at what I did in the deleted branch (moving the classes first in bareme ipp, then merging), it shouldn't be too different. 
Maybe @cbenz can help to make up for the wild PR deleting ;).

**Comment by benjello** [comment]
@fpagnoux we will try fix this.
Et bonnes vacances !

**Comment by benjello** [comment]
@cbenz : I followed @fpagnoux prescription but I still have some [failing tests](https://github.com/openfisca/openfisca-france/pull/559).
At least one of them has to do with update_legislation and it might also be that we point to the wrong branch of openfisca-core (master instead of baremes-pp. Can you have a look ? It is on my [baremes-ipp branch](https://github.com/benjello/openfisca-france/tree/baremes-ipp)

**Comment by cbenz** [comment]
@benjello What can I do here? Has this changed since my last commits on `update_legislation`?

**Comment by benjello** [comment]
@cbenz : I am on something else for now. I will get bak to you ASAP

**Comment by benjello** [comment]
@cbenz: I am dealing with this. Just make sure the the problems with the [parametric reforms](https://travis-ci.org/openfisca/openfisca-france) works ;-)
It is worthy to spend some time ont this to test it extensively.

**Comment by fpagnoux** [comment]
Outdated

**Pull request closed without merging**
