### PR TITLE
WIP: Add f2fa in the calculation of taxable income

### PR DESCRIPTION
**Pull request by edarin**
Still some doubts about if it was a good idea to add it to `rev_cat_rvcm`. Don't have a perfect panorama of the consequences.

### CODE REVIEW

**Comment by cbenz** [comment]
@benjello If you can have a quick look ^^

**Comment by benjello** [comment]
Seems ok but I do not have to go through it complet ely. If the PR can't wait à week go o'n and I will review it when I will do my merge.

I didn't look at at the tests but you definitively should check that f2fa start date is correctly handled.

**Comment by edarin** [comment]
**I- Comparison with the implementation of 2fa in M**

I looked how Bercy implemented this box, I think we got everything they have thought of. But furthermore we have introduced also this box into the calculation of ISF via `rev_cap_lib`.

**II- `rev_cap_rvcm` and/or `rev_cap_lib` ?**

After further thought adding f2fa to `rev_cap_rvcm` is a problem because for example in the calculation of `bouclier_rev` the variable `rvcm_plus_abat` which is based on `rev_cap_rvcm` is added to `rev_cap_lib`.

But in`rev_cap_lib` there is already `f2fa` ...

This oddity appears also in the calculation of `rev_coll`. (I think these two are the only ones)

Nevertheless I'm still wondering why `f2fa` doesn't belong to `rev_cap_rvcm`.

**Comment by edarin** [comment]
Might be interesting too to create a test for this  ?

**Comment by benjello** [comment]
SInce it mainly french fiscal stuff, i respond in french.
rev_cap_lib représente les revenus des capitaux soumis à prélèvement libératoire
rev_cat_rvcm représente [les revenus catégoriels des revenus des valeurs et capitaux mobiliers](http://www.impots.gouv.fr/portal/dgi/public/popup?espId=1&typePage=cpr02&docOid=documentstandard_6565&temNvlPopUp=true).

Si je ne m'abuse, ils sont mutuellement exclusifs.

**Comment by edarin** [comment]
En vrai je pense pas.

rev_cap_lib est exclusif de rev_cap_bar (les revenus du capital soumis au bareme).
On discute en vrai de deux définitions différentes : les revenus catégoriels qui servent à calculer l'impôt sur le revenu et dans lesquels sont inclus les revenus des valeurs et capitaux mobiliers donc cette fameuse case, et la notion plus générale de revenu du patrimoine/capital qui repose notamment sur rev_cap_lib dans openfisca.

En fait j'ai l'impression que ces deux notions se recoupent puisqu'elles font appel au même case cerfa:
-d'une part rev_cat_rvcm : [https://legislation.openfisca.fr/variables/rev_cat_rvcm](https://legislation.openfisca.fr/variables/rev_cat_rvcm)
- d'autre part: [rev_cap_lib](https://legislation.openfisca.fr/variables/rev_cap_lib) et [rev_cap_bar](https://legislation.openfisca.fr/variables/rev_cap_bar)

Y a un truc que je loupe.

**Comment by benjello** [comment]
Oui ils ne sont pas mutuellement exclusifs (j'ai oublié de virer cette phrase après avoir corrigé rev_cap_rvcm (tiré de ton post) en rev_cat_rvcm !

rev_cap_lib: ce sont les revenus du capital soumis au prélèvement libératoire (par opposition à ceux soumis au barème)
Donc  rev_cap_lib et rev_cap_bar sont mutuellement exclusifs.

**Comment by edarin** [comment]
Oups désolée..

Mais ça ne m'éclaire pas sur la différence entre rev_cat_rvcm et rev_cap ...

**Comment by benjello** [comment]
rev_cap est l'agrégat final de tous les revenus (nets) du capital. C'est une composante du revenu disponible  du ménage.

**Comment by edarin** [comment]
Ok But to conclude, with these informations f2fa should be include in both shouldn't it ?

But including in both leads to the problem I spoke about earlier.

**Comment by benjello** [comment]
We should be more explicit and detailed in bouclier_rev I think to avoid duplicates.
May be we should check how bouclier_rev is calculated in the M code.
BTW do you have ISF in the M code ?

**Comment by edarin** [comment]
Yes it is but for the moment I didn't get how bouclier_rev is computed (in M)...
Should I check also how rev_coll is computed in OpenFisca ?

I think it's the only measures that might duplicate some entry variable but I'm not sure ..

**Comment by benjello** [comment]
Yes, please,  do have a look at rev_coll.
It is the revenus_coolectifs part of the base ressource of some prestations sociales.
@fpagnoux should know more about what kind of revenu du capital enters the revenus collectifs.

Thank you @edarin

**Comment by edarin** [comment]
Superseded by #540

**Pull request closed without merging**
