### PR TITLE
CMU : Calculate prestation on last 12 months instead of using 12 factors

### PR DESCRIPTION
**Pull request by fpagnoux**
No more 12 factor !

No regression for mes aides due to capture of prestations

### CODE REVIEW

**Comment by cbenz** [comment]
The test [Couple qui touche une AL...](https://github.com/openfisca/openfisca-france/blob/48af9b85fc7b93f74cdce2e42f9d960adf05097a/openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_546cc5196c5820403d9b9c8d.yaml) does not pass.

Do you have an idea why?

**Comment by fpagnoux** [comment]
This test may have been updated. I'll have a look.

**Comment by fpagnoux** [comment]
This should hopefully fix the problem

**Comment by cbenz** [comment]
Sadly not, there are still errors with

* test_mes_aides_546cc5196c5820403d9b9c8d.yaml
* test_mes_aides_546cc5196c5820403d9b9c8d.yaml

Feel free to come see me if needed!

**Comment by fpagnoux** [comment]
I'm updating all the tests in another PR. Closing this one.

**Pull request closed without merging**
