### PR TITLE
Plf106 reform

### PR DESCRIPTION
**Pull request by benjello**
Migrating the plf2016 reforms
There is still a bug in ayrault_muet reform.
It seems that we cannot manipulate a variable that is provided by the reform, in the reform.

### CODE REVIEW

**Comment by fpagnoux** [comment]
Looking at it.

**Comment by fpagnoux** [comment]
It seems like there are scope limitations to [nesting classes](http://stackoverflow.com/questions/1765677/python-nested-classes-scope).

To avoid this problem, you can declare the classes in your reform out of the reform class, then call them with update_variable. See my last commit.

**Comment by benjello** [comment]
Thanks a lot @fpagnoux !

**Comment by benjello** [comment]
This seems GTM. 
@fpagnoux , @laem, @cbenz: could you guys review it ?

**Comment by cbenz** [comment]
Looking at it

**Comment by cbenz** [comment]
I suspect the PR to be based on `benjello/plf106_reform` and not `origin/plf106_reform`. The changelog includes too many things (like `numpy-1.11`). Right?

**Comment by benjello** [comment]
Yes it started on `benjello/plf106_reform`. But I tried to rebase  over master to have a clean PR.

**Comment by cbenz** [comment]
I know but still this PR is related to `benjello/plf106_reform` so could you push `origin/plf106_reform` to `benjello` to update this PR?

**Comment by benjello** [comment]
They are in sync on computer. I modified slightly the [benjello repo](https://github.com/benjello/openfisca-france/commits/plf106_reform) but it didn't propagate the changes ...

**Comment by cbenz** [comment]
Sorry, I was not up-to-date...

I merged your last commit (74b1226cb7af849e7470f769047620e8e2475147) on `origin` then I wait for the tests to run again then I merge.

**Comment by benjello** [comment]
Roger @cbenz

**Pull request merged**
